endeavourhealth-discovery/IMAPI

- api/pom.xml
- api/src/main/java/org/endeavourhealth/imapi/controllers/EntityController.java
- logic/pom.xml
- logic/src/main/java/org/endeavourhealth/imapi/logic/converters/EntityToImLang.java
- logic/src/test/java/org/endeavourhealth/imapi/logic/converters/EntityToImLangTest.java
Exclude api from unit test coverage
> Moved IMLang logic into logic

- api/src/main/java/org/endeavourhealth/imapi/controllers/EntityController.java
- dataaccess/src/main/java/org/endeavourhealth/imapi/dataaccess/helpers/XlsHelper.java
- dataaccess/src/main/java/org/endeavourhealth/imapi/dataaccess/repository/EntityTripleRepository.java
- logic/src/main/java/org/endeavourhealth/imapi/logic/service/EntityService.java
- logic/src/test/java/org/endeavourhealth/imapi/logic/service/EntityServiceTest.java
- models/src/main/java/org/endeavourhealth/imapi/model/dto/DownloadDto.java
I've just stubbed the code to build graph dtos for axioms as I'm not sure we want that in there as yet.
> text-definition changes (inferred/axioms) around download functionality

- node_api/src/services/query.service.ts
> Use built-in queries instead of custom

- node_api/src/builders/query/setQueryBuilder.ts
> Fix population of set editor builder when no name

- node_api/src/builders/entity/detailsBuilder.ts
- node_api/src/controllers/entityController.ts
- node_api/src/server.ts
- node_api/src/services/entity.service.ts
> Show all property-value pairs in details tree display

- api/src/main/java/org/endeavourhealth/imapi/controllers/EntityController.java
- api/src/main/java/org/endeavourhealth/imapi/dataaccess/EntityRepository.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/EntityService.java
- node_api/src/builders/entity/detailsBuilder.ts
- node_api/src/controllers/entityController.ts
- node_api/src/services/entity.service.ts
> Server error on bundleByPredicateExclusions call

- node_api/src/builders/query/displayBuilder.ts
> Display of set queries update - for new entityId (from) property

- api/src/main/java/org/endeavourhealth/imapi/model/iml/Where.java
Fixes endeavourhealth-discovery/IMAPI#228
> ECL conversion in Set Editor

- api/src/main/java/org/endeavourhealth/imapi/logic/service/EntityService.java
> UsedIn shows self

- api/src/main/java/org/endeavourhealth/imapi/filer/TTDocumentFiler.java
- api/src/main/java/org/endeavourhealth/imapi/filer/TTTransactionFiler.java
- api/src/main/java/org/endeavourhealth/imapi/filer/rdf4j/TTBulkFiler.java
- api/src/main/java/org/endeavourhealth/imapi/json/TTDocumentSerializer.java
- api/src/main/java/org/endeavourhealth/imapi/logic/exporters/ExcelSetExporter.java
- api/src/main/java/org/endeavourhealth/imapi/logic/exporters/SetExporter.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/EntityService.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/OSQuery.java
- api/src/main/java/org/endeavourhealth/imapi/transformengine/TTTranslator.java
- api/src/main/java/org/endeavourhealth/imapi/transformengine/TransformFactory.java
- api/src/main/java/org/endeavourhealth/imapi/transformengine/Transformer.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/ECLToIML.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/EqdPopToIMQ.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/EqdResources.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/IMLToECL.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/TTCompare.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/TTManager.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/TTToClassObject.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/TTToOWLEL.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/TTToObjectNode.java
Address Blocker and Critical sonar code smells (#244)
> #244 - Sonar code smells

- api/src/main/java/org/endeavourhealth/imapi/controllers/EntityController.java
- api/src/main/java/org/endeavourhealth/imapi/dataaccess/EntityRepository.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/EntityService.java
> New query isCodeValid for query using 'ask'

- api/src/main/java/org/endeavourhealth/imapi/controllers/FilerController.java
> Add TTDocument upload api

- api/build.gradle
- api/src/main/java/org/endeavourhealth/imapi/controllers/EntityController.java
- api/src/main/java/org/endeavourhealth/imapi/dataaccess/EntityTripleRepository.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/EntityService.java
> Add ask query for predicates + update autogen build

- api/src/main/java/org/endeavourhealth/imapi/controllers/FilerController.java
- api/src/main/java/org/endeavourhealth/imapi/dataaccess/UserRepository.java
> Folder selection - add/move not working properly + name validation for create folder

- api/src/main/java/org/endeavourhealth/imapi/controllers/FilerController.java
> Saving an edited folder entity bug

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/OpenSearchSender.java
- api/src/main/java/org/endeavourhealth/imapi/model/search/EntityDocument.java
- api/src/main/java/org/endeavourhealth/imapi/model/tripletree/TTIriRef.java
* Now includes entities without types
* Only holds/processes entity documents within the current batch
* Optimizations and memory leak fixes
> Reworked Opensearch Sender

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/QueryRepository.java
> Fix properties edit

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/SparqlConverter.java
> Copy of Adding a cohort fails - 500 error

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/EntityTripleRepository.java
- api/src/main/java/org/endeavourhealth/imapi/dataaccess/SparqlConverter.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/EntityService.java
- api/src/main/resources/application.properties
Added EntityReferenceNode fetch to repository layer (single SPARQL)
Added default ordering to get(Grand)Children (order int then name string) Code cleanup
> Result ordering and optimisations

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/EntityTripleRepository.java
> Navigation to QMUL CEG concept set library fails

- api/src/main/java/org/endeavourhealth/imapi/logic/service/EntityService.java
> Navigation fails to go to CSET_OralNSAIDs

- api/src/main/java/org/endeavourhealth/imapi/logic/service/ProvService.java
- api/src/main/java/org/endeavourhealth/imapi/vocabulary/IM.java
> Editing an entity creates a 'Creation' Activity Type provenance entity

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/SparqlConverter.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/Property.java
> Issue with isNull/null in queries

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/SparqlConverter.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/Property.java
> Issue with isNull/null in ts interface autogen

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/FileRepository.java
- api/src/main/java/org/endeavourhealth/imapi/vocabulary/IM.java
- api/src/main/java/org/endeavourhealth/imapi/vocabulary/ODS.java
- api/src/main/java/org/endeavourhealth/imapi/vocabulary/ORG.java
Additional data consumed from ODS import
Restructured Organisation model
Replaced System.out/err with LOG.info/warn
Removed existing IM ODS concepts
> ODS import

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/EntityRepository.java
- api/src/main/java/org/endeavourhealth/imapi/dataaccess/QueryRepository.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/QueryService.java
- api/src/main/java/org/endeavourhealth/imapi/model/search/SearchResponse.java
> QueryIM to return missing data for searchResponse (totalCount, page number, searchTerm) + getTypesByIris + getEntitySummariesByIris

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/EntityRepository.java
- api/src/main/java/org/endeavourhealth/imapi/dataaccess/OpenSearchSender.java
> Use im:scheme for code scheme, falling back to graph if no im:scheme present

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/OpenSearchSender.java
- api/src/main/java/org/endeavourhealth/imapi/model/search/Binding.java
- api/src/main/java/org/endeavourhealth/imapi/model/search/EntityDocument.java
Added missing prefix to SPARQL
Exit early if there's a problem
Extracted Binding to public class (to allow serialization)
> OpenSearch fixes

- api/src/main/java/org/endeavourhealth/imapi/logic/service/QueryDescriptor.java
> Property name duplication in query builder display

- api/src/main/java/org/endeavourhealth/imapi/logic/service/QueryDescriptor.java
> relative to display missing from description (displayLabel)

- api/src/main/java/org/endeavourhealth/imapi/logic/service/QueryDescriptor.java
> Missing display logic in IMAPI for queries

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/EntityRepository2.java
> Tree node names are missing in Add property

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/ProvRepository.java
> getProvHistory called from Provenance tab in IMDirectory returns a 500 error

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/EntityRepository2.java
> Undefined properties in graph view

- api/src/main/java/org/endeavourhealth/imapi/logic/service/QueryDescriptor.java
> Display value issues with date ranges

- api/src/main/java/org/endeavourhealth/imapi/logic/service/QueryDescriptor.java
> Query description does not update match description if already populated

- dependencies.gradle
> Concept creator local issue

- api/src/main/java/org/endeavourhealth/imapi/filer/TTEntityFiler.java
- api/src/main/java/org/endeavourhealth/imapi/filer/rdf4j/TTEntityFilerRdf4j.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/FilerService.java
> Concept Editor/Creator error on save - does save the entity

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/IMQToOS.java
> Searching im: in IMDirectory search goes to 500 page

- api/src/main/java/org/endeavourhealth/imapi/controllers/EclController.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/QueryDescriptor.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/ECLToIMQVisitor.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/IMQToECLBuilder.java
> Support inverse properties in UI display

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/EntityRepository.java
> Query display error

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/ConceptRepository.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/ConceptService.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/FunctionService.java
> Iri generator sometimes generates iri of entity already in db

- api/src/main/java/org/endeavourhealth/imapi/controllers/DataModelController.java
- api/src/main/java/org/endeavourhealth/imapi/dataaccess/DataModelRepository.java
- api/src/main/java/org/endeavourhealth/imapi/dataaccess/SparqlConverter.java
- api/src/main/java/org/endeavourhealth/imapi/logic/reasoner/Reasoner.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/DataModelService.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/QueryDescriptor.java
- api/src/main/java/org/endeavourhealth/imapi/model/iml/NodeShape.java
- api/src/main/java/org/endeavourhealth/imapi/model/iml/ParameterShape.java
- api/src/main/java/org/endeavourhealth/imapi/model/iml/PropertyShape.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/Assignable.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/Entail.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/Value.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/Where.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/EqdResources.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/IMQToECL.java
Related to Data Model Display pull request in IM Directotu
The Data model controller, service and Repository now returns a NodeShape to the client.
The Node Shape contains one or more Property Shapes. i.e. is a tree like structure generatged from the relational structure in IM
the Property Shape class can now be a property or a group containing properties and has some additional properties such as "hasValue","hasValueType" and "rangeType" to enable client display
"Or" properties have been removed from the ontology. They are unnecessary.
> DataModel Display API

- api/src/main/java/org/endeavourhealth/imapi/dataaccess/DataModelRepository.java
- api/src/main/java/org/endeavourhealth/imapi/dataaccess/EntityRepository.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/QueryDescriptor.java
- api/src/main/java/org/endeavourhealth/imapi/model/iml/PropertyRange.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/Assignable.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/Value.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/Where.java
- api/src/main/java/org/endeavourhealth/imapi/model/sql/IMQtoSQLConverter.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/EqdPopToIMQ.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/EqdResources.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/EqdToIMQ.java
- api/src/main/java/org/endeavourhealth/imapi/vocabulary/IM.java
- api/vocab.json
core ontology has new predicates of im:operator, im:units, im:isRelativeValue on data types with some new datatypes
These also reflected in the Assignable interface (Where and Value implementations) as well as Query descriptor.
This is a breaking change for the IMAPI and information manager but is not dependent on changes to IM directory a
> units of measure and eqd fixes

- api/src/test/java/org/endeavourhealth/imapi/utility/EnvHelperStepDefs.java
- api/src/test/resources/features/utility/EnvHelper.feature
> Parameterize step for simplification

- api/src/main/java/org/endeavourhealth/imapi/config/SecurityConfig.java
- api/src/test/java/org/endeavourhealth/imapi/CommonStepDefs.java
- api/src/test/java/org/endeavourhealth/imapi/CucumberRunner.java
- api/src/test/java/org/endeavourhealth/imapi/config/SecurityConfigStepDefs.java
- api/src/test/java/org/endeavourhealth/imapi/utility/EnvHelperStepDefs.java
- api/src/test/resources/features/config/SecurityConfig.feature
Refactored permissions setting
Extracted "Env var" stubs to common step defs
Added SecurityConfig test
> IMAPI-887 API endpoint permissions

- README.md
- api/src/main/java/org/endeavourhealth/imapi/filer/rdf4j/TTBulkFiler.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/TTManager.java
- api/src/test/java/org/endeavourhealth/imapi/CommonStepDefs.java
- api/src/test/java/org/endeavourhealth/imapi/transforms/TTManagerStepDefs.java
- api/src/test/resources/features/transforms/TTManager.feature
- aws_scripts/build.sh
- buildspec.yml
Added env vars to documentation
Cleaned up logging output
Parameterized build script
> TTManager (Preload) fix (& tests)

- api/src/main/java/org/endeavourhealth/imapi/controllers/AdminController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/CodeGenController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/CognitoController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/ConceptController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/ConfigController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/DataModelController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/EclController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/EntityController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/FilerController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/FunctionController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/GithubController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/QueryController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/SetController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/StatusController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/UserController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/WorkflowController.java
Enhanced API documentation by integrating OpenAPI annotations into various controllers. These annotations include operation summaries, descriptions, and parameter details, improving clarity and consistency for API consumers.
> Add OpenAPI annotations to API controllers

- api/src/main/java/org/endeavourhealth/imapi/logic/service/CodeGenService.java
- api/src/test/resources/features/service/codeGen.feature
Simplified and modularized the token replacement logic, adding clearer functions for specific replacements (e.g., arrays, typed properties). Updated "codify" and introduced "clean" for better handling of string transformations. Adjusted templates to support consistent namespace and token formatting.
> Refactor token replacement logic in CodeGenService

- api/src/main/java/org/endeavourhealth/imapi/logic/service/CodeGenService.java
- api/src/main/java/org/endeavourhealth/imapi/model/codegen/CodeGenTemplate.java
Ensure proper handling of missing collection wrappers and template indexes in CodeGenService. Added default initializations for CodeGenTemplate properties to prevent potential null value issues."
> "Fix null handling and initialize defaults in CodeGen logic

- api/src/main/java/org/endeavourhealth/imapi/controllers/EclController.java
- api/src/main/java/org/endeavourhealth/imapi/controllers/QueryController.java
- api/src/main/java/org/endeavourhealth/imapi/logic/reasoner/LogicOptimizer.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/EclService.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/QueryDescriptor.java
- api/src/main/java/org/endeavourhealth/imapi/logic/service/QueryService.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/ECLStatus.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/IriLD.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/Match.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/Query.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/QueryRequest.java
- api/src/main/java/org/endeavourhealth/imapi/model/imq/Where.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/ECLSyntaxError.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/ECLToIMQ.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/ECLToIMQVisitor.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/IMQToECL.java
- api/src/main/java/org/endeavourhealth/imapi/transforms/ParserErrorListener.java
- api/src/test/java/org/endeavourhealth/imapi/transforms/ECLToIMQStepDefs.java
> Ds ecl editor
